#!/bin/bash
# 🔧 ИСПРАВЛЕНИЕ СИНХРОНИЗАЦИИ GIT → СЕРВЕР

echo "🎊🔥🔧 СИНХРОНИЗИРУЕМ СЕРВЕР С GITHUB! 🔧🔥🎊"
echo ""
echo "🎯 ПРОБЛЕМА: Сервер не видит последние commits из GitHub"
echo "💡 РЕШЕНИЕ: Принудительная синхронизация"

echo ""
echo "1️⃣ ПОДКЛЮЧАЕМСЯ К СЕРВЕРУ:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "ssh root@207.154.220.86"

echo ""
echo "2️⃣ ПЕРЕХОДИМ В ПРОЕКТ И ПРОВЕРЯЕМ СТАТУС:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "cd /var/www/ai/itsolar"
echo "pwd  # убедиться что в правильной папке"
echo "git status  # проверить состояние"
echo "git log --oneline -5  # последние 5 commits"

echo ""
echo "3️⃣ ПРИНУДИТЕЛЬНАЯ СИНХРОНИЗАЦИЯ:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "git fetch --all  # получить все изменения"
echo "git reset --hard origin/main  # принудительно синхронизировать с main"
echo "git pull origin main  # дополнительный pull"

echo ""
echo "4️⃣ ПРОВЕРЯЕМ ЧТО ФАЙЛ ОБНОВИЛСЯ:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "grep -n 'DRAG & DROP HANDLERS N' f/src/components/company/CompanySidebar.tsx"
echo "# Должно найти строку с твоими изменениями!"

echo ""
echo "5️⃣ ПЕРЕЗАПУСКАЕМ СЕРВИСЫ:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "pm2 restart all  # перезапуск всех процессов"
echo "pm2 status  # проверить статус"

echo ""
echo "6️⃣ ПРОВЕРЯЕМ В БРАУЗЕРЕ:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# Открой https://itsolar.pl/dashboard"
echo "# Нажми Ctrl+Shift+R (hard refresh)"
echo "# Проверь что изменения видны"

echo ""
echo "🔍 ДИАГНОСТИКА - ЕСЛИ НЕ РАБОТАЕТ:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo ""
echo "А) Проверить GitHub Actions:"
echo "   🌐 https://github.com/Solarpaletten/SOLAR/actions"
echo "   ✅ Должен быть зелёный ✓ для последнего commit"
echo "   ❌ Если красный ✗ - посмотри логи ошибок"

echo ""
echo "Б) Проверить webhook (если настроен):"
echo "   cd /var/www/ai/itsolar"
echo "   ls -la  # проверить права доступа"
echo "   git config --list  # проверить git настройки"

echo ""
echo "В) Проверить процессы PM2:"
echo "   pm2 logs --lines 50  # посмотри логи"
echo "   pm2 monit  # мониторинг в реальном времени"

echo ""
echo "Г) Принудительная пересборка frontend:"
echo "   cd f"
echo "   npm run build"
echo "   # Если сервер использует собранные файлы"

echo ""
echo "🚀 АВТОМАТИЗАЦИЯ НА БУДУЩЕЕ:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo ""
echo "Создай скрипт автосинхронизации:"
echo "nano /var/www/ai/itsolar/sync_with_github.sh"
echo ""
echo "#!/bin/bash"
echo "cd /var/www/ai/itsolar"
echo "echo '🔄 Синхронизация с GitHub...'"
echo "git fetch --all"
echo "git reset --hard origin/main"
echo "git pull origin main"
echo "echo '🚀 Перезапуск сервисов...'"
echo "pm2 restart all"
echo "echo '✅ Синхронизация завершена!'"
echo ""
echo "chmod +x sync_with_github.sh"

echo ""
echo "🎯 ИСПОЛЬЗОВАНИЕ:"
echo "   ./sync_with_github.sh  # запуск синхронизации"

echo ""
echo "🎊🔥🚀 ПОСЛЕ ВЫПОЛНЕНИЯ ЭТИХ ШАГОВ: 🚀🔥🎊"
echo ""
echo "✅ Сервер будет синхронизирован с GitHub"
echo "✅ Твои изменения будут видны на https://itsolar.pl"
echo "✅ 'DRAG & DROP HANDLERS N' появится на сервере"
echo "✅ CompanySidebar.tsx будет актуальный"

echo ""
echo "💡 ГЛАВНЫЙ УРОК:"
echo "   git push → GitHub ✅"
echo "   GitHub → Сервер ❌ (нужна ручная синхронизация)"
echo "   Решение: git pull на сервере после каждого push"

echo ""
echo "🌟 ИДЕАЛЬНЫЙ WORKFLOW:"
echo "   1. Работаешь локально"
echo "   2. git push origin main"
echo "   3. SSH на сервер + ./sync_with_github.sh"
echo "   4. Проверяешь результат на itsolar.pl"

echo ""
echo "🚀 ГОТОВ К СИНХРОНИЗАЦИИ!"